### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bigmikehoncho** [Wrdlbrnft/Searchable-RecyclerView-Demo#11]
Hi Xaver,

This is some amazing work! I was wondering if there was any license associated with it?

Please let me know when you get a chance, thanks!

**Comment by Wrdlbrnft** [comment]
Everything I publish here on GitHub is using the MIT license. I just added the license file to the repository.

**Comment by bigmikehoncho** [comment]
Awesome, thank you!
