### ISSUE TITLE
ItemExampleBinding

### ISSUE THREAD

**Issue by Hitexroid** [Wrdlbrnft/Searchable-RecyclerView-Demo#13]
Hi
ItemExampleBinding class is not exists !!!

<img src="http://s7.picofile.com/file/8265505784/Screenshot_51_.png" alt="ItemExampleBinding" style="width:304px;height:228px;">

**Comment by Wrdlbrnft** [comment]
You don't seem to be familiar with data binding. Binding classes are generated by the Android Gradle Plugin. You might have to build the project at least once for them to be resolved by the IDE.

**Comment by Hitexroid** [comment]
how to use that in eclipse ?

**Comment by Wrdlbrnft** [comment]
Don't know. You really shouldn't use Eclipse anymore. It's so terrible. Anyway it should work regardless of which IDE you are using, it's just a Gradle thing.

**Comment by Hitexroid** [comment]
ok thank you :(

**Comment by naylonmuhendis** [comment]
in android studio
add gradle module 


    dataBinding {
        enabled true
    }

and sync again
