### ISSUE TITLE
 generate mBinding

### ISSUE THREAD

**Issue by devPaw** [Wrdlbrnft/Searchable-RecyclerView-Demo#15]
hi 
I found something in your project. your layout with data tag is item_example but in your main activity code you write `private ActivityMainBinding mBinding;`
but i found that it should be like this `private ItemExampleBinding mBinding;`
And becuz of that ` mBinding.recyclerView` cant find recyclerView.
i think something is missing.
Thank you for your help
I'm waiting for the answer.

**Comment by Wrdlbrnft** [comment]
No, you are wrong. I don't even understand what you are saying. The project builds just fine as it is. If you are unfamiliar with data binding then you can learn about it [**here**](https://developer.android.com/topic/libraries/data-binding/index.html).
