### ISSUE TITLE
Slow algorithm with Big Array List

### ISSUE THREAD

**Issue by Cesarsk** [Wrdlbrnft/Searchable-RecyclerView-Demo#17]
Hi! Great project, I really do appreciate your work!

I have a performance problem with your filtering algorithm if I use a big ArrayList (almost 400k words) to filter.

Precisely, it lags and it takes some time to filter the word I'm searching for.

Do you have any suggestion on that?
That might be useful for a lot of people dealing with a lot of entries.

Thank you and have a nice day!

**Comment by Wrdlbrnft** [comment]
Are you filtering in a separate thread? The filtering should almost always be done in a separate thread even for small lists and especially for big ones like yours. Also you should segment your list into parts which you load when the user reaches the end (think endless scrolling) or at least when the user scrolls to somewhere near the end.

**Comment by Cesarsk** [comment]
Hi! Thank you so much for your comment.

Can you give me a direction on how to filter in a separate thread ?

I'm trying to think about it and doing it but I can't figure it out !

Have a nice day :)!

**Comment by Claffolo** [comment]
@Wrdlbrnft Hi! I'm a collaborator in Cesarsk's project. I read on the Android official API that the "performFiltering" method is implemented with the "@WorkedThread" annotation. This annotation ensures that the method is called with an invoke to a separate worker thread, and it's all done automatically under the hood. So we did a couple tests with a much smaller list, and we had no lag at all. Any cool idea on how to split or reduce the list on each iteration?

Thank you in advance for your time! :D

**Comment by Wrdlbrnft** [comment]
I have no idea what you have been testing, but `@WorkerThread` does absolutely nothing. It is just an annotation used for lint checks meant to indicate that a method must not get called on the main thread. `@WorkerThread` does automatically execute your method in a worker thread. 

And I can't help you with something so specific without seeing your code. I can just tell you again: perform the filtering in a separate thread, split the lists into smaller parts and load the next part only when the user reaches the end of the list. These two improvements should yield the biggest gain in your situation.

**Comment by Cesarsk** [comment]
We'll look into that.
That said, we implemented a filteringThread but still lags a lot.
We'll try to split our wordlist into smaller parts and filter them separately.
