### ISSUE TITLE
Searchable-RecyvlerView with GridView

### ISSUE THREAD

**Issue by joancolmenerodev** [Wrdlbrnft/Searchable-RecyclerView-Demo#2]
Hello I implemented your demo and it works fine, but there are moments that the animation messes up...

I've done two screenshoots refering the problem take a look : 

When I type something and the result is : http://i.imgur.com/Evsbf6i.png

BUT when I press back to hide the keyboard it goes : http://i.imgur.com/MoLJ8Lm.png

Do you know what exactly is the problem? Also I've oppened a post on Stackoverflow that is about your post  : http://stackoverflow.com/questions/34889264/recyclerview-add-emptyview

Thanks.

**Comment by Wrdlbrnft** [comment]
It seems you already figures out what the problem was.
