### ISSUE TITLE
gradle dependency for using as library

### ISSUE THREAD

**Issue by kpradeepkumarreddy** [Wrdlbrnft/Searchable-RecyclerView-Demo#20]
can i have gradle dependency for using this project as library

**Comment by Wrdlbrnft** [comment]
I have no idea what you are talking about.

**Comment by kpradeepkumarreddy** [comment]
i want to include your project as a library in my project.

**Comment by Wrdlbrnft** [comment]
But this project is not a library, it's an application. If you want to implement something similar then just look at implementation of this project - its not complicated.
